### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by cah-briangantzler** [martndemus/ember-invoke-action#1]
I had been thinking of writing just this add-on the last month or so. 

Couple of suggestions:

First: The intent of sending an action from a component, is that if the action is not supplied, the action is ignored. I believe your case of strict action is attempting to validate a mandatory action. Mandatory actions should really be validated in the didReceiveAttrs to ensure the component was complete rather that wait til the action was invoked to determine if it should be mandatory or not. See https://github.com/dockyard/ember-one-way-input/blob/master/addon/components/one-way-input.js#L92

Second: Since sendAction is ONLY valid on components, allowing the use of a mixin seems to imply that it may be available elsewhere. If they are including your add-on, I assume the intent is to use your add-on, so I would suggest instead using an initializer to inject the functions onto component directly. This would negate the need for them importing or remembering to add the mixin to the components they would use this function on.

**Comment by martndemus** [comment]
Could you submit a PR for the second part?

**Comment by cah-briangantzler** [comment]
Not new to ember, but new to doing that. So PR you mean Pull Request not Proposal I am suspecting.

Soon as I get the time I will do that

**Comment by cah-briangantzler** [comment]
The more I look at this, and the actual sendAction code. The sendAction code actually does everything you need, it just doesnt return the value, and Im wondering why. It would seem a PR to ember proper to just add a return in the correct place would do it all. Possibly even implement the mandatory action, which might be served better as a mandatory parmater array.

**Comment by martndemus** [comment]
`sendAction` is the old way to call actions, 'Closure' actions is the new way.
Heres a screencast about closure actions: https://www.emberscreencasts.com/posts/76-closure-actions-in-ember-20-components-passing-functions

**Comment by cah-briangantzler** [comment]
Sorry for taking so long to get back. PTO and conferences.

I am aware of how closure actions work. Heres what I discovered while attempting to implement this.

Currently the sendAction provided by ember performs a check to see if the action is a function, if so, then also checks if it is a closure action. If the action is a function, it then executes it NOT returning the value. If the action is a string, it looks up the action and executes it.

This add-on attempts to circumvent the function portion of sendAction. If it is a function, the function is executed WITH the return value. If it is a string, it then calls sendAction (which wont find a function and execute the string portion of sendAction)

If you look at EXACTLY what sendAction does when it is a function, this add-on was not performing near the checks that send action already does. When attempting to perform the SAME checks so you the developer would not lost that functionality, most the checks were private. In order to perform them I had to duplicate the code, at which point I had completely reproduced the sendAction exactly with the only difference being the return statement on the function execution.

I looked into the ember slack channel and asked there. sendAction is there for backward compatibility. All new code you write use closure both in the component, but also in the use of a component. Current components will work. New components will use the closure call `this.attr.action()`. Since all new uses of components you will be using closure syntax, there will not be a conflict nor a need to do this. sendAction will most likely be removed when support for string actions are removed. 

At this point I decided there was no reason for this add-on.

**Comment by martndemus** [comment]
This addon never meant to emulate `sendAction`, this addon is all about helping developers reduce the amount of code they need to write to properly handle closure actions.

**Comment by cah-briangantzler** [comment]
I would agree if you remove the "sendAction" from the following code. Having it in the code is what makes if a "sendAction" replacement. Sorry for my misunderstanding of the intent.

```
if (typeof action === 'string') {
    object.sendAction(actionName, ...args);
  } else if (typeof action === 'function') {
    return action(...args);
  } else {
    assert(`No invokable action ${actionName} was found`, false);
  }
```

**Comment by cah-briangantzler** [comment]
that being said, now that I more correctly understand your intent. What I proposed was using an initializer to inject the desired methods onto a component so that merely installing the add-on would accomplish the goal..

As soon as I finish the pull request Im doing for ember-power-select, I will make a pull request for this if you still wish me to.

**Comment by cah-briangantzler** [comment]
Have the code written, but having difficulty running tests. I get the following

Uncaught Error: Assertion Failed: Ember Views require jQuery between 1.7 and 2.1

listed in bower.json is 
    "jquery": "^1.11.3",
which is clearly acceptable.

There must be something installed on my system that is interferring, but I don't know what Im able to run all my tests on all my other projects and even a few other addons I have forked....

I can send the code I have so you can look at it if you wish, but at this point I cant verify it with the tests :(

**Comment by cah-briangantzler** [comment]
So jquery 1.12 was released and there is a bug with the assertion in ember that is preventing the tests from running. Removing the ^ in the bower.json or upgrading jquery to 2.1.4 fixes the problem
