### ISSUE TITLE
Offer to Maintain

### ISSUE THREAD

**Issue by bryanaka** [martndemus/ember-invoke-action#11]
Hey @martndemus,

I am not sure to the reasons why this is now unmaintained but it sorta came out of the blue with no deprecation warnings. 

If you think that this is no longer a good idea to introduce a new action paradigm, then I would like to propose we have a deprecation path for those looking to remove this dependency. I would be happy to help lead that effort.

If that isn't the case and it's just that you are too busy to maintain, I would like to offer to help maintain.

**Comment by oskarrough** [comment]
Hey, any updates? :) This addon is also used by https://github.com/smile-io/ember-cli-stripe/issues/32.

**Comment by martndemus** [comment]
I just invited all three of you to be a collaborator. If you ping me with a NPM username I'll also set you up there.

**Comment by miguelcobain** [comment]
@martndemus npm user is @miguelcobain

**Comment by bryanaka** [comment]
mine is `@bryanaka`. Thanks!

**Comment by miguelcobain** [comment]
@bryanaka I don't see any other collaborators on npm yet: https://www.npmjs.com/package/ember-invoke-action

So, we can't really publish new releases.

**Comment by bryanaka** [comment]
@miguelcobain good point, I'll reopen until thats resolved too 😅

**Comment by martndemus** [comment]
I sent you both invites yesterday and today, so you should be good.

**Comment by miguelcobain** [comment]
I confirm that I have access.
Don't know why I didn't get any e-mail or why the npm page of the project doesn't display any other collaborators.

👍

**Comment by bryanaka** [comment]
Also confirmed access now. Closing
